### ISSUE TITLE
MAC OS support

### ISSUE THREAD

**Issue by junhyeokahn** [agoessling/bazel_bootlin#1]
Hello,
Thanks for this great repo!

In any case, do you have any plan to support mac os with Apple silicon chip?
Also, I am wondering if I can build a target for linux machine deployment on Mac OS host.

Thanks in advance.

**Comment by agoessling** [comment]
This repo simply wraps, for use in Bazel, the toolchains that Bootlin provides.  Bootlin only provides cross compiling toolchains for linux x86_64 host to linux target of various architectures.
